linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  gosec:
    excludes:
      - G402
      - G404
  revive:
    rules:
      - name: var-declaration
        disabled: true

linters:
  enable-all: true
  disable:
    - funlen
    - nlreturn
    - wrapcheck
    - gomnd
    - cyclop
    - err113
    - exhaustruct
    - wsl
    - lll
    - dupl
    - varnamelen
    - gomoddirectives
    - gocognit
    - tagliatelle
    - errorlint
    - gofumpt
    - noctx
    - gosec
    - testpackage
    - gci
    - musttag
    - depguard
    - ireturn
    - dogsled
    - perfsprint
    - mnd
    - nilnil
    - execinquery
    - intrange
    - exportloopref
